services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Kolkata
    volumes:
      - /Users/yash/docker/volumes/calibre/config:/config
      - ./ingest:/cwa-book-ingest
      - /Users/yash/docker/volumes/calibre/library:/calibre-library
    restart: always
    networks:
      - proxy

  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
    restart: always
    platform: linux/amd64
    volumes:
      # This is where the books will be downloaded to, usually it would be
      # the same as whatever you gave in "calibre-web-automated"
      - ./ingest:${INGEST_DIR:-/cwa-book-ingest}
    networks:
      - proxy

  cloudflarebypassforscraping:
    image: ghcr.io/sarperavci/cloudflarebypassforscraping:latest
    restart: always
    platform: linux/amd64

networks:
  proxy:
    external: true
