services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /home/yash/docker/volumes/hoarder/data:/data
    ports:
      - 3022:3000
    env_file:
      - .env
    environment:
      DATA_DIR: /data
      BROWSER_WEB_URL: http://chrome:9222
      CRAWLER_FULL_PAGE_ARCHIVE: "true"
      MEILI_ADDR: http://meilisearch:7700
      NEXTAUTH_URL: http://localhost:3000
      INFERENCE_TEXT_MODEL: gemini-exp-1206
      INFERENCE_IMAGE_MODEL: gemini-exp-1206
      OPENAI_BASE_URL: https://generativelanguage.googleapis.com/v1beta/
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
