services:
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: always
    volumes:
      - /Users/yash/docker/volumes/hoarder/data:/data
    env_file:
      - .env
    networks:
      - default
      - proxy
    environment:
      DATA_DIR: /data
      BROWSER_WEB_URL: http://chrome:9222
      CRAWLER_FULL_PAGE_ARCHIVE: 'true'
      MEILI_ADDR: http://meilisearch:7700
      NEXTAUTH_URL: http://localhost:3000
      INFERENCE_TEXT_MODEL: gemini-exp-1206
      INFERENCE_IMAGE_MODEL: gemini-exp-1206
      OPENAI_BASE_URL: https://generativelanguage.googleapis.com/v1beta/

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: always
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - default

  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: always
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: 'true'
    volumes:
      - meilisearch:/meili_data
    networks:
      - default

volumes:
  meilisearch:

networks:
  default:
  proxy:
    external: true
