services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    # ports:
    #   - '8086:8086'
    networks:
      - default
      - proxy
    volumes:
      - /Users/yash/docker/volumes/influxdb-v2/data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=yash
      - DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influxdb_password
      - DOCKER_INFLUXDB_INIT_ORG=homelab
      - DOCKER_INFLUXDB_INIT_BUCKET=homelab
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influxdb_admin_token
    secrets:
      - influxdb_password
      - influxdb_admin_token

volumes:
  influxdb-data:

networks:
  default:
  proxy:
    external: true

secrets:
  influxdb_password:
    file: /Users/yash/docker/secrets/influxdb_v2_password.txt
  influxdb_admin_token:
    file: /Users/yash/docker/secrets/influxdb_v2_admin_token.txt
