services:
  couchdb-obsidian-livesync:
    image: docker.io/oleduc/docker-obsidian-livesync-couchdb:master
    container_name: couchdb-obsidian-livesync
    restart: always
    environment:
      SERVER_URL: http://localhost:5984
      COUCHDB_USER: obsidian
      COUCHDB_PASSWORD: obsidian
      COUCHDB_DATABASE: livesync
    platform: linux/amd64
    volumes:
      - /Users/yash/docker/volumes/couchdb/data:/opt/couchdb/data
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
