services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    user: '0'
    restart: unless-stopped
    # ports:
    #   - '3456:3000'
    networks:
      - default
      - proxy
    volumes:
      - /Users/yash/docker/volumes/grafana/data:/var/lib/grafana
      - /Users/yash/docker/configs/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      # InfluxDB Data Source (configure this if you are using InfluxDB)
      - GF_DATABASE_TYPE=sqlite3 # Configure this for local grafana db
      - GF_DATABASE_NAME=/var/lib/grafana/grafana.db
      - INFLUXDB_PASSWORD_FILE=/run/secrets/influxdb_password
      - INFLUXDB_ADMIN_TOKEN_FILE=/run/secrets/influxdb_admin_token
    secrets:
      - grafana_password
      - influxdb_password
      - influxdb_admin_token

volumes:
  grafana-data:

networks:
  default:
  proxy:
    external: true

secrets:
  grafana_password:
    file: /Users/yash/docker/secrets/grafana_password.txt
  influxdb_password:
    file: /Users/yash/docker/secrets/influxdb_v2_password.txt
  influxdb_admin_token:
    file: /Users/yash/docker/secrets/influxdb_v2_admin_token.txt
